/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReplayIndexRouteImport } from './routes/replay/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as ReplaySlugRouteImport } from './routes/replay/$slug'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayIndexRoute = ReplayIndexRouteImport.update({
  id: '/replay/',
  path: '/replay/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaySlugRoute = ReplaySlugRouteImport.update({
  id: '/replay/$slug',
  path: '/replay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/replay/$slug': typeof ReplaySlugRoute
  '/journal/': typeof JournalIndexRoute
  '/replay/': typeof ReplayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/replay/$slug': typeof ReplaySlugRoute
  '/journal': typeof JournalIndexRoute
  '/replay': typeof ReplayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/replay/$slug': typeof ReplaySlugRoute
  '/journal/': typeof JournalIndexRoute
  '/replay/': typeof ReplayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/journal/$slug'
    | '/replay/$slug'
    | '/journal/'
    | '/replay/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/about' | '/journal/$slug' | '/replay/$slug' | '/journal' | '/replay'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/journal/$slug'
    | '/replay/$slug'
    | '/journal/'
    | '/replay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ReplaySlugRoute: typeof ReplaySlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ReplayIndexRoute: typeof ReplayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/': {
      id: '/replay/'
      path: '/replay'
      fullPath: '/replay/'
      preLoaderRoute: typeof ReplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$slug': {
      id: '/replay/$slug'
      path: '/replay/$slug'
      fullPath: '/replay/$slug'
      preLoaderRoute: typeof ReplaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JournalSlugRoute: JournalSlugRoute,
  ReplaySlugRoute: ReplaySlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ReplayIndexRoute: ReplayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
